<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitaeaae43362aa40beab53ace21bec2202
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitaeaae43362aa40beab53ace21bec2202::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitaeaae43362aa40beab53ace21bec2202::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitaeaae43362aa40beab53ace21bec2202::$classMap;

        }, null, ClassLoader::class);
    }
}
